export const logo='../assets/images/OIP.jpg'
export const title='Online Shopping'
export const banner='../assets/images/banner.png'
export const signUpLogo = '../assets/images/signUp.jpg'
export const cartLogo ='../assets/images/cart.jpg'
export const profileLogo = '../assets/images/profile.png'
export const categoryLogo = '../assets/images/category.jpg'
export const productLogo = '../assets/images/product.jpg'
